"""Init

Revision ID: 6a2a07fd39aa
Revises: 67ab204b7cdf
Create Date: 2024-03-27 11:10:01.347521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2a07fd39aa'
down_revision: Union[str, None] = '67ab204b7cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET banned = false")
    op.alter_column('users', 'banned', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    # ### end Alembic commands ###
