"""Description of changes

Revision ID: 8360ce23a2b9
Revises: ae62f15f80e9
Create Date: 2024-03-22 02:13:10.133282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8360ce23a2b9'
down_revision: Union[str, None] = 'ae62f15f80e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('photos', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('photos', sa.Column('rating', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'photos', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'rating')
    op.drop_column('photos', 'owner_id')
    op.drop_column('photos', 'description')
    # ### end Alembic commands ###
