"""empty message

Revision ID: 962de72a6e4f
Revises: 8360ce23a2b9
Create Date: 2024-03-22 02:31:36.614690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962de72a6e4f'
down_revision: Union[str, None] = '8360ce23a2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photos_owner_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_owner_id_fkey', 'photos', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
